hugging_face_model_path: google/flan-t5-base # for better results: google/flan-t5-xl
local_model_path: data/model
local_tokenizer_path: data/tokenizer
device: auto
max_new_tokens: 50
text_splitter:
  chunk_size: 500
  chunk_overlap: 200
hugging_face_embedding_model_path: nreimers/MiniLM-L6-H384-uncased
vector_store_path: data/vector_store
test_document_path: "data/Transcript Otter - A1.txt"
prompt_template: |
  Use the following pieces of context to answer the question at the end.
  If you don't know the answer, just say "This wasn't discussed in the call.", don't try to make up an answer.
  Use three sentences maximum and keep the answer as concise as possible.
  Chat History: {chat_history}
  Context: {context}
  Question: {question}
  Helpful Answer:
prompt_input_variables:
  - chat_history
  - context
  - question
documents_to_retrieve: 5
rerank_documents: True
